[project]
name = "ragbuilder"
dynamic = ["version"] 
description = "RagBuilder SDK - Create optimal Production-ready RAG pipelines"
authors = [
    {name = "Ashwin Aravind", email = "ashwin@krux.ai"},
    {name = "Aravind Parameswaran", email = "aravind@krux.ai"},
]
requires-python = ">=3.10,<4"
readme = "README.md"
license = {text = "Apache-2.0"}

dependencies = [
    "chromadb>=1.5.9",
    "langchain-chroma>=1.1.0",
    "beautifulsoup4>=4.12.0",
    "requests>=2.32.5",
    "urllib3>=2.6.3",
    "scikit-optimize>=0.10.2",
    "markdown>=3.5.0",
    "datasets>=2.18.0",
    "fastapi>=0.142.2,<1",
    "jinja2>=3.1.6",
    "langchain>=1.4.3,<2",
    "langchain-classic>=1.0.8,<2",
    "langchain-community==0.4.1",
    "langchain-core>=1.6.6,<2",
    "langchain-huggingface>=1.2.2,<2",
    "langchain-openai>=1.6.7,<2",
    "optuna",
    "platformdirs",
    "pydantic>=2.0.0",
    "python-dotenv",
    "ragas>=0.4.3,<0.5",
    "rerankers",
    "rich>=13.0.0",
    "sentence-transformers",
    "tenacity==8.4.2",
    "rank-bm25",
    "uvicorn>=0.30.0",    
]

# Optional dependencies
[project.optional-dependencies]
graph = [
    "neo4j>=5.23.0",
    "langchain-community[neo4j]"
]

vectorstores = [
    "elasticsearch>=8.0.0",
    "faiss-cpu>=1.7.4",
    "pinecone-client>=3.0.0",
    "pymilvus>=2.3.0",
    "qdrant-client>=1.7.0",
    "weaviate-client>=3.25.0",    
]

# Document processing
document_processors = [
    "pymupdf>=1.23.0",
    "python-docx>=1.0.0",
    "pikepdf>=8.11.0",
    "pandoc>=2.3",
    "pypdf>=3.17.0",
    "markdown>=3.5.0",
    "beautifulsoup4>=4.12.0",
    "unstructured[all-docs]>=0.11.0",
]

all = [
    "ragbuilder[graph]",
    "ragbuilder[vectorstores]",
    "ragbuilder[document_processors]",
]

[project.scripts]
ragbuilder = "ragbuilder.ragbuilder:main"

[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/ragbuilder/_version.py"
version_scheme = "python-simplified-semver"

